// Copyright(c) 2016 - 2021 Code 4 Game, Org. All Rights Reserved.
// Don't edit this, it will be generated by builder.

#pragma once

#define GLTFFORUE4_MAJOR_VERSION 2
#define GLTFFORUE4_MINOR_VERSION 0
#define GLTFFORUE4_PATCH_VERSION 9
#define GLTFFORUE4_BUILD_NUMBER 372321269
